### ISSUE TITLE
Remove WebVR support

### ISSUE THREAD

**Issue by bnolan** [bnolan/scenevr-web#111]
The current webVR support isn't complete, you can't chat, click, teleport, edit preferences. So instead of having a broken implementation, we'll redirect users to use Janus for rift mode, and we can focus on providing an excellent 2D, mobile and google cardboard experience.

I recommend re-adding webvr support in a few months using a good polyfill, once the webvr APIs have stabilised, and about to hit master.

**Comment by brianpeiris** [comment]
:( Maybe @jcarpenter can help address some of your issues with the API.

**Comment by bnolan** [comment]
The API is good and it works well, it's just that my implementation was too half-assed. I use a lot of dom elements to render UI, and there's no easy cross-browser way to render them in the rift at the moment. I know this will make you guys sad, but this is just an interim measure, I think no-support is better than half-baked from my side. :)

**Comment by brianpeiris** [comment]
I see. How do you render UI in Janus? Does it support DOM rendering?

**Comment by bnolan** [comment]
Working on re-adding support.

https://github.com/scenevr/client/commit/1853740ff720ed75731746d29ccfb94b72c58b20

I've got a windows installer that installs a browser + creates a shortcut to launch scene in VR mode.
