### ISSUE TITLE
Release firefox pointerlock on close tab

### ISSUE THREAD

**Issue by bnolan** [bnolan/scenevr-web#80]
Apparently firefox doesn't release itself.

**Comment by bnolan** [comment]
cc @widdershin.

**Comment by bnolan** [comment]
I can't replicate this with firefox 36.04 on os x  - can someone please reopen with replication steps.

**Comment by Widdershin** [comment]
Replicates in my Firefox profile, but not with a fresh profile. It's probably a conflict with Tree Style Tabs or one of these addons:

Name|Version
----|-------
Auto Reload|1.20
FindBar Tweak|1.4.18
Greasemonkey|3.1
Hola Better Internet|1.7.126
HTTPS-Everywhere|4.0.3
JSONovich|1.9.7.1
LastPass|3.1.1
LeechBlock|0.6.7.1
Multiple Tab Handler|0.8.2015030601
QuickDrag|2.1.3.23
Reddit Enhancement Suite|4.5.4
Restartless Restart|9
Socialite|1.5.1
Tab Badge|1.19
Tree Style Tab|0.15.2014120101
Windows Shortcuts|0.2
µBlock|0.8.6.0

I wouldn't worry about it.

**Comment by bnolan** [comment]
Sweet thanks. :)
